group test
imaitre/menu-service pull request #24
Opened 2021-02-07 20:50 UTC by diegolucasilva

pending:: redis embedded

2021-02-08 00:26 UTC, padovese commented
mongo*

2021-02-09 01:12 UTC, padovese requested changes

2021-02-09 01:12 UTC, padovese commented on src/test/kotlin/com/maitre/menuservice/adapter/group/in/get/GetGroupHandlerTest.kt
> +                .uri("/group?menu_id=MENU_af60830b-d190-43bf-afcb-f5cc2656ea25")
mocka esse get, usa o do menu como exemplo, ta no PR #25

2021-02-10 17:13 UTC, padovese requested changes

2021-02-10 17:13 UTC, padovese commented on src/main/kotlin/com/maitre/menuservice/adapter/group/in/update/UpdateGroupHandlerImpl.kt
> +                    created(URI("IMPLEMENTAR_HATEOS_SELF${serverRequest.path()}/${it.id}"))
The resource is already created. A better response for this use case should be a 200 OK.

2021-02-10 17:13 UTC, padovese commented on src/main/kotlin/com/maitre/menuservice/domain/group/entity/Group.kt
> +import java.util.*
Don't use wildcards.

2021-02-10 17:13 UTC, padovese commented on src/main/kotlin/com/maitre/menuservice/exception/GroupNotFoundException.kt
> +class GroupNotFoundException(id: String) : RuntimeException("Group not found. $id")
Let `group_id=$id`
The logs engines like splunk, kibana and cloudWatch use key=value format to index their logs.

2021-02-10 17:13 UTC, padovese commented on src/test/kotlin/com/maitre/menuservice/adapter/group/in/create/CreateGroupHandlerTest.kt
> + class CreateGroupHandlerTest {
Use test profile only for integration testes. And rename/realocate it to indicate that is an integration test.

2021-02-10 17:13 UTC, padovese commented on src/test/kotlin/com/maitre/menuservice/adapter/group/in/create/CreateGroupHandlerTest.kt
> + class CreateGroupHandlerTest {
Also, mock the repository using whenever().then()

2021-02-10 17:13 UTC, padovese commented on src/test/kotlin/com/maitre/menuservice/adapter/group/in/get/GetGroupHandlerTest.kt
> +internal class GetGroupHandlerTest{
Same as above.

2021-02-10 17:13 UTC, padovese commented on src/test/kotlin/com/maitre/menuservice/domain/group/usecases/CreateGroupUseCaseTest.kt
> +        whenever(saveGroupPort.save(any<Group>())).thenReturn(Mono.just(group))
duplicated lines.

2021-02-10 17:13 UTC, padovese commented on src/test/kotlin/com/maitre/menuservice/domain/group/usecases/CreateGroupUseCaseTest.kt
> +        verify(saveGroupPort, times(1)).save(any<Group>())
you can also verify if the getMenuPort is being called.

2021-02-10 17:13 UTC, padovese commented on src/test/kotlin/com/maitre/menuservice/domain/group/usecases/GetGroupsByMenuIdUseCaseTest.kt
> +                .verifyComplete()
This test is ok, but as a tip, if you are working with flux, you can mock a list of N and then verify a count of N events emitted.

2021-02-15 19:26 UTC, diegolucasilva commented on src/main/kotlin/com/maitre/menuservice/domain/group/entity/Group.kt
> +import java.util.*
done

2021-02-15 19:27 UTC, diegolucasilva commented on src/main/kotlin/com/maitre/menuservice/exception/GroupNotFoundException.kt
> +class GroupNotFoundException(id: String) : RuntimeException("Group not found. $id")
This exception is used in 2 situations. I think we can refactor all this type of exception and create only ResourceNotFoundException that can receive a complete message.

2021-02-15 19:28 UTC, diegolucasilva commented on src/test/kotlin/com/maitre/menuservice/adapter/group/in/create/CreateGroupHandlerTest.kt
> + class CreateGroupHandlerTest {
mock doesnt work... pending a issue later

2021-02-15 19:28 UTC, diegolucasilva commented on src/test/kotlin/com/maitre/menuservice/adapter/group/in/get/GetGroupHandlerTest.kt
> +internal class GetGroupHandlerTest{
done

2021-02-15 19:29 UTC, diegolucasilva commented on src/test/kotlin/com/maitre/menuservice/domain/group/usecases/CreateGroupUseCaseTest.kt
> +        whenever(saveGroupPort.save(any<Group>())).thenReturn(Mono.just(group))
done

2021-02-15 19:29 UTC, diegolucasilva commented on src/test/kotlin/com/maitre/menuservice/domain/group/usecases/CreateGroupUseCaseTest.kt
> +        verify(saveGroupPort, times(1)).save(any<Group>())
done

2021-02-16 19:26 UTC, diegolucasilva commented on src/main/kotlin/com/maitre/menuservice/adapter/group/in/update/UpdateGroupHandlerImpl.kt
> +                    created(URI("IMPLEMENTAR_HATEOS_SELF${serverRequest.path()}/${it.id}"))
done

2021-02-16 20:12 UTC, padovese approved these changes

2021-02-16 20:12 UTC, merged