Feature/delete cascade
imaitre/menu-service pull request #30
Opened 2021-02-16 22:24 UTC by diegolucasilva

2021-02-16 22:30 UTC, padovese commented on src/main/kotlin/com/maitre/menuservice/adapter/group/out/GroupAdapter.kt
> +import com.maitre.menuservice.domain.group.port.out.persistence.*
altera na sua ide essa config

2021-02-17 23:24 UTC, diegolucasilva commented on src/main/kotlin/com/maitre/menuservice/adapter/group/out/GroupAdapter.kt
> +import com.maitre.menuservice.domain.group.port.out.persistence.*
done

2021-02-18 02:42 UTC, padovese requested changes
Esse PR é só a cascata vinda do menu, não ta incluso a cascata vindo do grupo, certo?

2021-02-18 02:42 UTC, padovese commented on src/main/kotlin/com/maitre/menuservice/domain/menu/usecases/DeleteMenuUseCase.kt
> +                .then(deleteMenuPort.delete(id))
Aqui não basta deletar os grupos, tem que deletar também os produtos desses grupos.
Desta forma que está, vai ficar produto sem grupo associado.

2021-02-23 14:15 UTC, padovese approved these changes

2021-02-23 14:15 UTC, merged